### ISSUE TITLE
[Front] Compression

### ISSUE THREAD

**Issue by its-colby** [autonomys/auto-drive#11]
- add compression (on upload) and decompression (on download) (both on client-side) to all files to free some network bandwidth
- ensure that the compression algorithm is listed within within the data somewhere, likely at the top section where the root node is. This way, we can smoothly transition to either not have compression algorithms or change the algorithm and still have everything backwards compatible.

**Comment by clostao** [comment]
This means to compress on the client & decompress on the server?

**Comment by its-colby** [comment]
No, it means to compress and decompress on the client. The point would be to minimize the size of the file over the network whether it be from the client to the backend or from the backend to the blockchain.

**Comment by its-colby** [comment]
Folders will not be compressed, as the data of folders needs to be unaltered in order to appropriately point to the name of the files it contains. However, files within a folder, will of course be compressed. Essentially, anything in the DATA section of a node should be compressed. @clostao
