### ISSUE TITLE
[Issue] Uploading the same file with the same encryption results in different CID

### ISSUE THREAD

**Issue by EmilFattakhov** [autonomys/auto-drive#123]
Uploading the same file with no encryption doesn't create duplicates. 

But uploading the same file with the same encryption mechanism (same password) results in different CIDs. 
Examples of such files:

1. https://auto-drive-demo.netlify.app/drive/metadata/bafkr6iaiuaif2vxedoej6shh7q3pvgos5fmlpbg5jg4szwad5pa3rcxhze
2. https://auto-drive-demo.netlify.app/drive/metadata/bafkr6ia4sjwxyzlyhm7qkeu2pz5ocgwsi3wdl74kc3heldlrpyrkh3upyy
3. https://auto-drive-demo.netlify.app/drive/metadata/bafkr6ibxm3dcn2oambrpadzgnrvsol27ncu2q63rniwi6no5z3lzrs4qhe

They're all encrypted with the password "password"

**Comment by clostao** [comment]
It seems that you were encrypting the files:

Notice that encryption algorithm is setup.

<img width="660" alt="image" src="https://github.com/user-attachments/assets/9a69daa6-3fec-42c5-8878-f9933a521cf0" />

**Comment by EmilFattakhov** [comment]
Closing the issue as it's an expected behaviour. Thank you for checking @clostao!
