### ISSUE TITLE
[Feature] Dynamically show uploading process in the CLI

### ISSUE THREAD

**Issue by EmilFattakhov** [autonomys/auto-drive#124]
Perhaps we're able to change the function signature and return a few things:

1. Dynamically show uploading %, status of completion
2. Return the CID and/or shareable link upon successful upload

**Comment by clostao** [comment]
This was handled at https://github.com/autonomys/auto-sdk/pull/210

Upload methods return a Promise<string> that resolves into the file/folder cid. Optionally, a `onProgess` method could passed in the uploadOptions argument that would be called every time a chunk of the file/folder is uploaded.

**Comment by EmilFattakhov** [comment]
Thanks Carlos!
