### ISSUE TITLE
[Front] Local Cache

### ISSUE THREAD

**Issue by its-colby** [autonomys/auto-drive#49]
Utilizing Local Storage, implement a local cache for files and folders, so that the user does not need to constantly query for frequently used files/folders.

**Comment by clostao** [comment]
localStorage has a maximum size of 5MB per website. 

Might be a better option [IndexedDB](https://medium.com/@songusepython/the-best-way-of-browser-storage-more-than-localstorage-and-indexdb-d275cf78589a#:~:text=IndexedDB%20has%20a%20much%20larger,article%20is%20to%20introduce%20localForage!)

**Comment by its-colby** [comment]
Yep, IndexedDB looks like the right approach. For now, you can use whatever is more convenient to develop, since its a low priority. But, long term, we will probably want IndexedDB. @clostao
