### ISSUE TITLE
[Front] Download folders from Backend

### ISSUE THREAD

**Issue by its-colby** [autonomys/auto-drive#5]

**Comment by clostao** [comment]
Files are downloadable right now.

**Comment by clostao** [comment]
How should folder download would work? Compressed to zip files?

**Comment by its-colby** [comment]
Good question. Let's have folder download compress it to a zip file. That seems to be the standard for this kind of thing.

**Comment by clostao** [comment]
Backend implementation at: https://github.com/autonomys/auto-drive/pull/28
