### ISSUE TITLE
[Front — Small Addition] Sharing Files/Folders should include link

### ISSUE THREAD

**Issue by its-colby** [autonomys/auto-drive#55]
Sharing should not "exclusively" be by username. Similar to Google Drive, users should be able to copy a link or search by handle to share.

**Comment by clostao** [comment]
How would this work along the download credit limitation feature. For implementing the monthly download limit we need the user to be authenticated for downloading a file (for reducing the user's download credits). If the user generates a link to the file the person that receives, should be able to download the file? If that's the case who would "pay" for that download?  

@its-colby

**Comment by its-colby** [comment]
Not necessarily the case. If a non-registered user (or user without enough credits) views the link, they should be shown the appropriate error message. This will need to be done in the route handling on the backend. @clostao

**Comment by its-colby** [comment]
In the Profile section, there should also be a "copy handle" button
