### ISSUE TITLE
[Front] More UI/UX Fixes

### ISSUE THREAD

**Issue by its-colby** [autonomys/auto-drive#87]
- "add or drop files" button →  Let's remove this button from the "global feed" page and especially the "shared with me" page
- On the "trash" page, the message "Files you mark as deleted will appear here." should use the term "removed" instead of "deleted"
- On the "shared with me" page, "No shared with you files yet" should be changed to "No files have been shared with you yet". Additionally, "Share files with others by clicking the share button on the top right" should say ".....share button on any of your files" instead of "...on the top right"
- In the "metadata" page of a file that I created, in the "owners" section, I still see "admin" followed by my public ID. Additionally, I also see a "delete" button instead of the correct "remove" button

**Comment by clostao** [comment]
@its-colby I left this ticket on review. Please, mark it as completed or provide feedback if sth else is missing.
